{'application': False,
 'author': 'Nedas Zilinskas',
 'auto_install': False,
 'category': 'Sales,Website',
 'contributors': 'Nedas Zilinskas',
 'currency': 'EUR',
 'data': ['views/templates.xml'],
 'demo': [],
 'depends': ['website_sale'],
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'http://minilini.com/page/start',
 'maintainer': 'Nedas Zilinskas',
 'name': 'Horizontal Attributes Filters',
 'price': 20.0,
 'qweb': [],
 'summary': 'Horizontal dropdowns of attributes and sorting',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '11.0.1.0.0',
 'website': 'http://nedaszilinskas.com'}
